version: '3'

services:
  dj-gunicorn:
    image: dj-gunicorn:1.0
    volumes:
      - ./static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    image: nginx:2.0
    volumes:
      - ./static:/static
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dj-gunicorn
  
volumes:
  static: