version: '3'

services:
  django_gunicorn:
    image: django_gunicorn:1.2
    volumes:
      - ./static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.2
    volumes:
      - ./static:/static
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  
volumes:
  static: