version: '3'

services:
  django:
    image: django:1.0
    volumes:
      - ./static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.0
    volumes:
      - ./static:/static
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django
  
volumes:
  static: